Repository buku-masjid/buku-masjid, pull requests merged in 2023-09, with the labels that each got.

#4 Issue 1: Setup Docker
  Dockerfile
  README.md
  docker-compose.yml
Labels: enhancement

#5 feat: Perbaikan serta penambahan dokumentasi.
  README.md
Labels: documentation

#13 Task 12: Fix request query in button not showing this month
  resources/views/public_reports/in_months.blade.php
  resources/views/public_reports/in_out.blade.php
  resources/views/public_reports/in_weeks.blade.php
Labels: bug
